accounts/urls.py
from accounts import views
from django.urls import path

from django.urls.conf import include

"""the app_name variable provided for {% url 'namespace-for-url-ofproject:the nameofviewinpath' and relate it with id%}"""
app_name='accounts'


urlpatterns = [
    path('register',views.register,name="register"),
    path('profile',views.profile,name="profile"),
    path('profile/edit',views.profile_edit,name="profile_edit"),
    
]

job/urls.py
from unicodedata import name
from job import views
from django.urls import path

from django.urls.conf import include
from job import viewsapi
"""the app_name variable provided for {% url 'namespace-for-url-ofproject:the nameofviewinpath' and relate it with id%}"""
app_name='job'


urlpatterns = [
    path('',views.job_list,name="job_list"),
    path('add',views.add_job,name="add_job"),
    path('<str:slug>',views.job_detail,name="job_detail"),
    #Generic Class Based Views Api
    path('api/jobs',viewsapi.Job_ListApi.as_view(),name='job_list_api'),
    path('api/jobs/<int:id>',viewsapi.Job_DetailApi.as_view(),name='job_detail_api'),
    path('api/category',viewsapi.Category_ListApi.as_view(),name='category_list_api'),
    path('api/category/<int:id>',viewsapi.Category_DetailApi.as_view(),name='category_detail_api'),
    path('api/apply',viewsapi.Apply_ListApi.as_view(),name='apply_list_api'),
    path('api/apply/<int:id>',viewsapi.Apply_DetailApi.as_view(),name='apply_detail_api'),
    #End of Generic Class Based Views Api

    #Function Based Views Api
    path('api/jobsfunc',viewsapi.job_list_func_api , name='job_list_func_api'),
    path('api/jobsfunc/<int:id>',viewsapi.job_detail_func_api , name='job_detail_func_api'),
    path('api/categoryfunc',viewsapi.Category_list_func_api , name='Category_list_func_api'),
    path('api/categoryfunc/<int:id>',viewsapi.Category_detail_func_api , name='Category_detail_func_api'),
    path('api/applyfunc',viewsapi.Apply_list_func_api , name='Apply_list_func_api'),
    path('api/applyfunc/<int:id>',viewsapi.Apply_detail_func_api , name='Apply_detail_func_api'),
    #End of Function Based Views Api
    
]

project/urls.py
from unicodedata import name
from django import views
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace="accounts")),
    path('admin/', admin.site.urls),
    path('jobs/',include('job.urls',namespace="jobs")),
    path('contactus/',include('contact.urls',namespace="contact")),
    path('api-auth/',include("rest_framework.urls")),
    path('blog/',include('blog.urls',namespace="blogs")),
    path('',include('home.urls',namespace="homepage")),
    
]

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class Profile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE)
    city=models.ForeignKey("City",related_name='user_city', on_delete=models.CASCADE,blank=True,null=True)
    phone_number=models.CharField(max_length=15)
    image=models.ImageField(upload_to='profile/')

    def __str__(self):
        return str(self.user)


#SIGNAL IS HAPPEN AFTER WE POST_SAVE THAT'S MEAN AFTER SAVING ANEW USER WE WILL HAVE A NEW PROFILE

@receiver(post_save,sender=User)
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)




class City(models.Model):
    name=models.CharField(max_length=30)

    def __str__(self):
        return str(self.name)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import fields

from accounts.models import Profile


class SignupForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','email','password1','password2']

class UserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','first_name','last_name','email']



class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=['city','phone_number','image']

accounts/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from .forms import SignupForm,ProfileForm,UserForm
from .models import Profile
from django.urls import reverse
# Create your views here.

def register(request):
    if request.method=='POST':
        form=SignupForm(request.POST)
        if form.is_valid:
            form.save()
            #send username and password to authenticate and login to profile after signup
            username=form.cleaned_data['username']
            password=form.cleaned_data['password1']
            user=authenticate(username=username,password=password)
            login(request,user)
            return redirect('/accounts/profile')
            
    else:
        form=SignupForm()

    return render(request,'registration/signup.html',{'signupform':form})


def profile(request):
    profile = Profile.objects.get(user=request.user)
    return render(request,'accounts/profile.html',{'profile': profile})


def profile_edit(request):
    profile = Profile.objects.get(user=request.user)

    if request.method=='POST':
        user_form=UserForm(request.POST,instance=request.user)
        profile_form=ProfileForm(request.POST,request.FILES,instance=profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            myprofile_form=profile_form.save(commit=False)
            myprofile_form.user = request.user
            myprofile_form.save()

            return redirect(reverse('accounts:profile'))

    else:
        user_form=UserForm(instance=request.user)
        profile_form=ProfileForm(instance=profile)



    return render(request,'accounts/profile_edit.html',{"User_Form":user_form,"Profile_Form":profile_form})

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                



                <div class="col-lg-6 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Profile Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li> Name: <span>{{profile}}</span></li>
                                <li>Email: <span>{{profile.user.email}}</span></li>
                                <li>Phone: <span>{{profile.phone_number}}</span></li>
                                <li>Address: <span>{{profile.city}}</span></li>
                                
                            </ul>
                            
                        </div>
                        <div class="p-5">
                            <a class="boxed-btn3 w-100" href="{% url 'accounts:profile_edit' %}">Edit Profile</a>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endblock body %}

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    
                    
                    
                    <div class="apply_job_form white-bg">
                        <h4>Edit Your Profile</h4>
                        <form method='POST' enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form User_Form %}
                            {% bootstrap_form Profile_Form %}
                            
                            {% buttons %}
                                <button class="boxed-btn3 w-100" type="submit">Save Changes</button>
                            {% endbuttons %}

                                
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>

    {% endblock body %}